import type { UserProperty } from './types';

/**
 * Mock data for user-owned properties.
 * Fields aligned with PropertySummaryResponse.
 */
export const mockUserProperties: UserProperty[] = [
  {
    propertyId: 'a1b2c3d4-e5f6-7890-abcd-111111111111',
    streetAddress: '123 Nguyễn Huệ, Phường Bến Nghé',
    landSizeM2: 120.5,
    usableSizeM2: 95.0,
    widthM: 5.5,
    lengthM: 22.0,
    areaSqft: 1022.58,
    description: 'Modern townhouse in District 1 with 3 bedrooms and rooftop terrace.',
    status: 'AVAILABLE',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400',
    location: {
      locationId: 'loc-001',
      cityName: 'Hồ Chí Minh',
      districtName: 'Quận 1',
      wardName: 'Phường Bến Nghé',
      latitude: 10.7731,
      longitude: 106.7030,
    },
    propertyType: {
      propertyTypeId: 'pt-001',
      propertyTypeName: 'Townhouse',
      propertyTypeCode: 'TOWNHOUSE',
      propertyCategoryName: 'Residential',
      propertyCategoryCode: 'RESIDENTIAL',
    },
    attributes: [
      {
        attributeId: 'attr-001',
        attributeCode: 'BEDROOMS',
        attributeName: 'Bedrooms',
        dataType: 'NUMBER',
        icon: 'bed-double',
        unit: null,
        valueNumber: 3,
        valueText: null,
        valueBoolean: null,
        displayValue: '3',
      },
      {
        attributeId: 'attr-002',
        attributeCode: 'BATHROOMS',
        attributeName: 'Bathrooms',
        dataType: 'NUMBER',
        icon: 'bath',
        unit: null,
        valueNumber: 2,
        valueText: null,
        valueBoolean: null,
        displayValue: '2',
      },
      {
        attributeId: 'attr-003',
        attributeCode: 'HAS_BALCONY',
        attributeName: 'Balcony',
        dataType: 'BOOLEAN',
        icon: 'scan-eye',
        unit: null,
        valueNumber: null,
        valueText: null,
        valueBoolean: true,
        displayValue: 'Có',
      },
      {
        attributeId: 'attr-004',
        attributeCode: 'HAS_AC',
        attributeName: 'Air Conditioning',
        dataType: 'BOOLEAN',
        icon: 'wind',
        unit: null,
        valueNumber: null,
        valueText: null,
        valueBoolean: true,
        displayValue: 'Có',
      },
      {
        attributeId: 'attr-005',
        attributeCode: 'FURNISHING',
        attributeName: 'Furnishing',
        dataType: 'TEXT',
        icon: 'sofa',
        unit: null,
        valueNumber: null,
        valueText: 'Fully Furnished',
        valueBoolean: null,
        displayValue: 'Fully Furnished',
      },
    ],
    amenities: [
      { amenityId: 'am-001', amenityName: 'Swimming Pool' },
      { amenityId: 'am-002', amenityName: 'Gym' },
    ],
    media: [],
  },
  {
    propertyId: 'a1b2c3d4-e5f6-7890-abcd-222222222222',
    streetAddress: '456 Lê Lợi, Phường Bến Thành',
    landSizeM2: 85.0,
    usableSizeM2: 72.0,
    widthM: 4.0,
    lengthM: 18.0,
    areaSqft: 775.01,
    description: 'Cozy apartment near Bến Thành Market, perfect for investment.',
    status: 'DRAFT',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400',
    location: {
      locationId: 'loc-002',
      cityName: 'Hồ Chí Minh',
      districtName: 'Quận 1',
      wardName: 'Phường Bến Thành',
      latitude: 10.7726,
      longitude: 106.6980,
    },
    propertyType: {
      propertyTypeId: 'pt-002',
      propertyTypeName: 'Apartment',
      propertyTypeCode: 'APARTMENT',
      propertyCategoryName: 'Residential',
      propertyCategoryCode: 'RESIDENTIAL',
    },
    attributes: [],
    amenities: [],
    media: [],
  },
  {
    propertyId: 'a1b2c3d4-e5f6-7890-abcd-333333333333',
    streetAddress: '789 Trần Hưng Đạo, Phường 7',
    landSizeM2: 200.0,
    usableSizeM2: 160.0,
    widthM: 8.0,
    lengthM: 25.0,
    areaSqft: 1722.24,
    description: 'Spacious villa with garden and swimming pool in District 5.',
    status: 'AVAILABLE',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400',
    location: {
      locationId: 'loc-003',
      cityName: 'Hồ Chí Minh',
      districtName: 'Quận 5',
      wardName: 'Phường 7',
      latitude: 10.7580,
      longitude: 106.6900,
    },
    propertyType: {
      propertyTypeId: 'pt-003',
      propertyTypeName: 'Villa',
      propertyTypeCode: 'VILLA',
      propertyCategoryName: 'Residential',
      propertyCategoryCode: 'RESIDENTIAL',
    },
    attributes: [],
    amenities: [],
    media: [],
  },
  {
    propertyId: 'a1b2c3d4-e5f6-7890-abcd-444444444444',
    streetAddress: '12 Nguyễn Văn Trỗi, Phường 1',
    landSizeM2: 65.0,
    usableSizeM2: 55.0,
    widthM: 3.5,
    lengthM: 15.0,
    areaSqft: 592.02,
    description: 'Studio apartment with city view, recently renovated.',
    status: 'RESERVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400',
    location: {
      locationId: 'loc-004',
      cityName: 'Hồ Chí Minh',
      districtName: 'Quận Phú Nhuận',
      wardName: 'Phường 1',
      latitude: 10.8020,
      longitude: 106.6710,
    },
    propertyType: {
      propertyTypeId: 'pt-004',
      propertyTypeName: 'Studio',
      propertyTypeCode: 'STUDIO',
      propertyCategoryName: 'Residential',
      propertyCategoryCode: 'RESIDENTIAL',
    },
    attributes: [],
    amenities: [],
    media: [],
  },
  {
    propertyId: 'a1b2c3d4-e5f6-7890-abcd-555555555555',
    streetAddress: '88 Đường Số 2, Phường Thảo Điền',
    landSizeM2: 300.0,
    usableSizeM2: 250.0,
    widthM: 12.0,
    lengthM: 25.0,
    areaSqft: 2691.0,
    description: 'Luxury riverside villa in Thảo Điền with private dock.',
    status: 'AVAILABLE',
    thumbnailUrl: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=400',
    location: {
      locationId: 'loc-005',
      cityName: 'Hồ Chí Minh',
      districtName: 'Thành phố Thủ Đức',
      wardName: 'Phường Thảo Điền',
      latitude: 10.8060,
      longitude: 106.7350,
    },
    propertyType: {
      propertyTypeId: 'pt-003',
      propertyTypeName: 'Villa',
      propertyTypeCode: 'VILLA',
      propertyCategoryName: 'Residential',
      propertyCategoryCode: 'RESIDENTIAL',
    },
    attributes: [],
    amenities: [],
    media: [],
  },
  // Generate more properties for pagination testing
  ...Array.from({ length: 10 }).map((_, i) => ({
    propertyId: `generated-id-${i}`,
    streetAddress: `${100 + i} Lê Duẩn, Phường Bến Nghé`,
    landSizeM2: 150.0 + (i * 10),
    usableSizeM2: 120.0 + (i * 10),
    widthM: 6.0,
    lengthM: 25.0,
    areaSqft: (120.0 + (i * 10)) * 10.764,
    description: `Premium business district property #${i + 1}`,
    status: (i % 3 === 0 ? 'AVAILABLE' : i % 3 === 1 ? 'DRAFT' : 'SOLD') as UserProperty['status'],
    thumbnailUrl: `https://images.unsplash.com/photo-${1600000000000 + i}?w=400&auto=format&fit=crop`,
    location: {
      locationId: 'loc-001',
      cityName: 'Hồ Chí Minh',
      districtName: 'Quận 1',
      wardName: 'Phường Bến Nghé',
      latitude: 10.7780 + (i * 0.001),
      longitude: 106.7000 + (i * 0.001),
    },
    propertyType: {
      propertyTypeId: 'pt-001',
      propertyTypeName: 'Townhouse',
      propertyTypeCode: 'TOWNHOUSE',
      propertyCategoryName: 'Residential',
      propertyCategoryCode: 'RESIDENTIAL',
    },
    attributes: [
      {
        attributeId: `attr-gen-bed-${i}`,
        attributeCode: 'BEDROOMS',
        attributeName: 'Bedrooms',
        dataType: 'NUMBER',
        icon: 'bed-double',
        unit: null,
        valueNumber: 2 + (i % 3),
        valueText: null,
        valueBoolean: null,
        displayValue: `${2 + (i % 3)}`,
      },
    ],
    amenities: [] as { amenityId: string; amenityName: string }[],
    media: [] as { mediaId: string; mediaType: string; mediaUrl: string; thumbnailUrl: string | null; isPrimary: boolean; displayOrder: number }[],
  })),
];
