import type { OwnerPropertySummary } from '@/entities/property';

export const MOCK_OWNER_PROPERTIES: OwnerPropertySummary[] = [
  {
    property_id: 'mock-001',
    street_address: '12 Nguyễn Huệ, Quận 1',
    status: 'AVAILABLE',
    land_size_m2: 120,
    usable_size_m2: 100,
    descriptions: 'Căn hộ cao cấp view sông, nội thất đầy đủ, thoáng mát.',
    property_type_info: {
      property_type_id: 'pt-1',
      property_type_name: 'Căn hộ',
      property_type_code: 'APARTMENT',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-1',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 1',
      ward_name: 'Phường Bến Nghé',
      latitude: 10.7769,
      longitude: 106.7009,
    },
    media: [
      {
        media_id: 'm-001',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a1', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 3, value_text: null, value_boolean: null, display_value: '3' },
      { attribute_id: 'a2', attribute_code: 'BATHROOMS', attribute_name: 'Phòng tắm', data_type: 'NUMBER', icon: null, unit: null, value_number: 2, value_text: null, value_boolean: null, display_value: '2' },
    ],
    owner_id: 'owner-001',
    owner_name: 'Nguyễn Văn An',
    owner_phone: '0901234567',
    owner_email: 'an.nguyen@email.com',
    has_active_proposal: true,
  },
  {
    property_id: 'mock-002',
    street_address: '45 Lê Lợi, Quận 3',
    status: 'AVAILABLE',
    land_size_m2: 200,
    usable_size_m2: 180,
    descriptions: 'Nhà phố mặt tiền đường lớn, kinh doanh thuận tiện.',
    property_type_info: {
      property_type_id: 'pt-2',
      property_type_name: 'Nhà phố',
      property_type_code: 'TOWNHOUSE',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-2',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 3',
      ward_name: 'Phường 6',
      latitude: 10.7830,
      longitude: 106.6927,
    },
    media: [
      {
        media_id: 'm-002',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a3', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 4, value_text: null, value_boolean: null, display_value: '4' },
      { attribute_id: 'a4', attribute_code: 'FLOORS', attribute_name: 'Số tầng', data_type: 'NUMBER', icon: null, unit: null, value_number: 3, value_text: null, value_boolean: null, display_value: '3' },
    ],
    owner_id: 'owner-002',
    owner_name: 'Trần Thị Bích',
    owner_phone: '0912345678',
    owner_email: 'bich.tran@email.com',
    has_active_proposal: true,
  },
  {
    property_id: 'mock-003',
    street_address: '88 Đinh Tiên Hoàng, Bình Thạnh',
    status: 'PENDING',
    land_size_m2: 500,
    usable_size_m2: 450,
    descriptions: 'Biệt thự sân vườn rộng, hồ bơi riêng, an ninh 24/7.',
    property_type_info: {
      property_type_id: 'pt-3',
      property_type_name: 'Biệt thự',
      property_type_code: 'VILLA',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-3',
      city_name: 'Hồ Chí Minh',
      district_name: 'Bình Thạnh',
      ward_name: 'Phường 22',
      latitude: 10.8031,
      longitude: 106.7136,
    },
    media: [
      {
        media_id: 'm-003',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a5', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 5, value_text: null, value_boolean: null, display_value: '5' },
      { attribute_id: 'a6', attribute_code: 'BATHROOMS', attribute_name: 'Phòng tắm', data_type: 'NUMBER', icon: null, unit: null, value_number: 4, value_text: null, value_boolean: null, display_value: '4' },
    ],
    owner_id: 'owner-003',
    owner_name: 'Phạm Minh Châu',
    owner_phone: '0923456789',
    owner_email: null,
  },
  {
    property_id: 'mock-004',
    street_address: '20 Võ Văn Tần, Quận 10',
    status: 'AVAILABLE',
    land_size_m2: 80,
    usable_size_m2: 75,
    descriptions: null,
    property_type_info: {
      property_type_id: 'pt-1',
      property_type_name: 'Căn hộ',
      property_type_code: 'APARTMENT',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-4',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 10',
      ward_name: 'Phường 4',
      latitude: 10.7720,
      longitude: 106.6680,
    },
    media: null,
    attributes: [
      { attribute_id: 'a7', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 2, value_text: null, value_boolean: null, display_value: '2' },
    ],
    owner_id: 'owner-004',
    owner_name: 'Lê Hoàng Dũng',
    owner_phone: '0934567890',
    owner_email: 'dung.le@email.com',
  },
  {
    property_id: 'mock-005',
    street_address: '55 Cách Mạng Tháng 8, Tân Bình',
    status: 'AVAILABLE',
    land_size_m2: 350,
    usable_size_m2: 320,
    descriptions: 'Văn phòng cho thuê nguyên sàn, vị trí trung tâm, tiện ích đầy đủ.',
    property_type_info: {
      property_type_id: 'pt-4',
      property_type_name: 'Văn phòng',
      property_type_code: 'OFFICE',
      property_category_id: 'pc-2',
      property_category_name: 'Thương mại',
      property_category_code: 'COMMERCIAL',
    },
    location_info: {
      location_id: 'loc-5',
      city_name: 'Hồ Chí Minh',
      district_name: 'Tân Bình',
      ward_name: 'Phường 12',
      latitude: 10.8018,
      longitude: 106.6573,
    },
    media: [
      {
        media_id: 'm-005',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [],
    owner_id: 'owner-005',
    owner_name: 'Hoàng Thị Emm',
    owner_phone: '0945678901',
    owner_email: 'emm.hoang@company.vn',
  },
  {
    property_id: 'mock-006',
    street_address: '7 Nguyễn Trãi, Quận 5',
    status: 'AVAILABLE',
    land_size_m2: 60,
    usable_size_m2: 55,
    descriptions: 'Studio hiện đại, view thành phố đẹp, thích hợp cho người độc thân.',
    property_type_info: {
      property_type_id: 'pt-1',
      property_type_name: 'Căn hộ',
      property_type_code: 'APARTMENT',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-6',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 5',
      ward_name: 'Phường 1',
      latitude: 10.7537,
      longitude: 106.6640,
    },
    media: [
      {
        media_id: 'm-006',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a8', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 1, value_text: null, value_boolean: null, display_value: '1' },
    ],
    owner_id: 'owner-006',
    owner_name: 'Vũ Quốc Phong',
    owner_phone: '0956789012',
    owner_email: null,
  },
  {
    property_id: 'mock-007',
    street_address: '100 Phạm Văn Đồng, Gò Vấp',
    status: 'AVAILABLE',
    land_size_m2: 250,
    usable_size_m2: 230,
    descriptions: 'Kho xưởng sạch sẽ, điện 3 pha, tiếp giáp đường xe tải.',
    property_type_info: {
      property_type_id: 'pt-5',
      property_type_name: 'Kho xưởng',
      property_type_code: 'WAREHOUSE',
      property_category_id: 'pc-2',
      property_category_name: 'Thương mại',
      property_category_code: 'COMMERCIAL',
    },
    location_info: {
      location_id: 'loc-7',
      city_name: 'Hồ Chí Minh',
      district_name: 'Gò Vấp',
      ward_name: 'Phường 7',
      latitude: 10.8345,
      longitude: 106.6836,
    },
    media: [
      {
        media_id: 'm-007',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: null,
    owner_id: 'owner-007',
    owner_name: 'Đặng Thị Giang',
    owner_phone: '0967890123',
    owner_email: 'giang.dang@business.com',
  },
  {
    property_id: 'mock-008',
    street_address: '32 Trần Hưng Đạo, Quận 1',
    status: 'AVAILABLE',
    land_size_m2: 150,
    usable_size_m2: 140,
    descriptions: 'Shophouse tầng trệt mặt tiền đường lớn, lý tưởng cho kinh doanh bán lẻ.',
    property_type_info: {
      property_type_id: 'pt-6',
      property_type_name: 'Shophouse',
      property_type_code: 'SHOPHOUSE',
      property_category_id: 'pc-2',
      property_category_name: 'Thương mại',
      property_category_code: 'COMMERCIAL',
    },
    location_info: {
      location_id: 'loc-8',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 1',
      ward_name: 'Phường Cầu Ông Lãnh',
      latitude: 10.7623,
      longitude: 106.6971,
    },
    media: [
      {
        media_id: 'm-008',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [],
    owner_id: 'owner-008',
    owner_name: 'Bùi Văn Hải',
    owner_phone: '0978901234',
    owner_email: 'hai.bui@store.vn',
  },
  {
    property_id: 'mock-009',
    street_address: '15 Hoàng Diệu, Quận 4',
    status: 'AVAILABLE',
    land_size_m2: 90,
    usable_size_m2: 85,
    descriptions: 'Nhà cấp 4 hẻm xe hơi, cần cải tạo, giá thấp hơn thị trường.',
    property_type_info: {
      property_type_id: 'pt-7',
      property_type_name: 'Nhà riêng',
      property_type_code: 'HOUSE',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-9',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 4',
      ward_name: 'Phường 8',
      latitude: 10.7567,
      longitude: 106.7032,
    },
    media: [
      {
        media_id: 'm-009',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a9', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 2, value_text: null, value_boolean: null, display_value: '2' },
    ],
    owner_id: 'owner-009',
    owner_name: 'Ngô Thị Khánh',
    owner_phone: '0989012345',
    owner_email: null,
  },
  {
    property_id: 'mock-010',
    street_address: '78 Phan Xích Long, Phú Nhuận',
    status: 'AVAILABLE',
    land_size_m2: 130,
    usable_size_m2: 120,
    descriptions: 'Căn hộ duplex thiết kế độc đáo, 2 tầng thông nhau.',
    property_type_info: {
      property_type_id: 'pt-1',
      property_type_name: 'Căn hộ',
      property_type_code: 'APARTMENT',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-10',
      city_name: 'Hồ Chí Minh',
      district_name: 'Phú Nhuận',
      ward_name: 'Phường 2',
      latitude: 10.7997,
      longitude: 106.6828,
    },
    media: [
      {
        media_id: 'm-010',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a10', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 3, value_text: null, value_boolean: null, display_value: '3' },
      { attribute_id: 'a11', attribute_code: 'BATHROOMS', attribute_name: 'Phòng tắm', data_type: 'NUMBER', icon: null, unit: null, value_number: 2, value_text: null, value_boolean: null, display_value: '2' },
    ],
    owner_id: 'owner-010',
    owner_name: 'Trịnh Quốc Linh',
    owner_phone: '0990123456',
    owner_email: 'linh.trinh@email.com',
  },
  {
    property_id: 'mock-011',
    street_address: '3 Ngô Gia Tự, Quận 10',
    status: 'VERIFIED',
    land_size_m2: 400,
    usable_size_m2: 380,
    descriptions: 'Đất nền dự án quy hoạch rõ ràng, hạ tầng hoàn chỉnh.',
    property_type_info: {
      property_type_id: 'pt-8',
      property_type_name: 'Đất nền',
      property_type_code: 'LAND',
      property_category_id: 'pc-3',
      property_category_name: 'Đất',
      property_category_code: 'LAND',
    },
    location_info: {
      location_id: 'loc-11',
      city_name: 'Hồ Chí Minh',
      district_name: 'Quận 10',
      ward_name: 'Phường 13',
      latitude: 10.7748,
      longitude: 106.6598,
    },
    media: [
      {
        media_id: 'm-011',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: null,
    owner_id: 'owner-011',
    owner_name: 'Phan Thị Mai',
    owner_phone: '0901112233',
    owner_email: 'mai.phan@invest.vn',
  },
  {
    property_id: 'mock-012',
    street_address: '66 Lạc Long Quân, Tân Bình',
    status: 'AVAILABLE',
    land_size_m2: 170,
    usable_size_m2: 160,
    descriptions: 'Nhà phố 3 tầng mới xây, nội thất cơ bản, khu dân cư yên tĩnh.',
    property_type_info: {
      property_type_id: 'pt-2',
      property_type_name: 'Nhà phố',
      property_type_code: 'TOWNHOUSE',
      property_category_id: 'pc-1',
      property_category_name: 'Nhà ở',
      property_category_code: 'RESIDENTIAL',
    },
    location_info: {
      location_id: 'loc-12',
      city_name: 'Hồ Chí Minh',
      district_name: 'Tân Bình',
      ward_name: 'Phường 8',
      latitude: 10.7876,
      longitude: 106.6523,
    },
    media: [
      {
        media_id: 'm-012',
        media_type: 'IMAGE',
        media_url: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
        thumbnail_url: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=400',
        is_primary: true,
        is_property_standard: true,
        display_order: 1,
      },
    ],
    attributes: [
      { attribute_id: 'a12', attribute_code: 'BEDROOMS', attribute_name: 'Phòng ngủ', data_type: 'NUMBER', icon: null, unit: null, value_number: 4, value_text: null, value_boolean: null, display_value: '4' },
      { attribute_id: 'a13', attribute_code: 'FLOORS', attribute_name: 'Số tầng', data_type: 'NUMBER', icon: null, unit: null, value_number: 3, value_text: null, value_boolean: null, display_value: '3' },
    ],
    owner_id: 'owner-012',
    owner_name: 'Lý Văn Nam',
    owner_phone: '0912233445',
    owner_email: 'nam.ly@email.com',
  },
];
