name: PR to Discord

permissions:
  contents: read
  pull-requests: read
  
on:
  pull_request:
    types: [opened, review_requested]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR to Discord
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"

          # lấy reviewer
          REVIEWERS=$(jq -r '.pull_request.requested_reviewers[].login' <<< '${{ toJson(github.event) }}')

          # mapping GitHub -> Discord ID
          declare -A MAP
          MAP["Hoang-Nguyen-Huy"]="@620091987336626238"
          MAP["HuyDiCode"]="@650208747141988365"
          MAP["nguyenhcp2004"]="@761822942740086808"
          MAP["ThanhTriIsCoding"]="@868924065874858004"
          MAP["toki-ai"]="@897685284286791732"

          TAGS=""
          for r in $REVIEWERS; do
            TAGS="$TAGS ${MAP[$r]}"
          done

          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🚀 New PR Created!\n**$PR_TITLE**\n$PR_URL\n👤 Author: $AUTHOR\n👀 Reviewers: $TAGS\"
          }"